namespace: dev-native

resources:
  - service.yml
  - configmap.yml
  - genesis.yml
  - validator.yml
  - ingress.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-pstake
    files:
      - configs/keys.json
      - configs/validators.json
  - name: pstake-scripts
    files:
      - scripts/create-val.sh
