resources:
- service.yaml
- configmap.yaml
- statefulset.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: test-addresses
  files:
  - configs/keys.json
  - configs/validators.json
