namespace: dev-core

resources:
  - service.yml
  - configmap.yml
  - genesis.yml
  - validator.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: test-addresses-persistencecore
    files:
      - configs/keys.json
      - configs/validators.json
