[global]
log_level = 'info'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'pstaked'
rpc_addr = 'http://pstake-genesis.dev-native.svc.cluster.local:26657'
grpc_addr = 'http://pstake-genesis.dev-native.svc.cluster.local:9090'
websocket_addr = 'ws://pstake-genesis.dev-native.svc.cluster.local:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'persistence'
key_name = 'persistence'
store_prefix = 'ibc'
max_gas = 2000000
fee_granter = ''
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'gaiad'
rpc_addr = 'http://gaia-genesis.dev-native.svc.cluster.local:26657'
grpc_addr = 'http://gaia-genesis.dev-native.svc.cluster.local:9090'
websocket_addr = 'ws://gaia-genesis.dev-native.svc.cluster.local:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'cosmos'
store_prefix = 'ibc'
max_gas = 2000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
clock_drift = '15s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
